import {
  ArbitrationInfo,
  BaroInfo,
  CycleInfo,
  FissureInfo,
  NightwaveInfo,
  RewardEval,
  RivenScanState,
  WorldstateSnapshot,
} from '../../shared/types'

const inHours = (h: number) => new Date(Date.now() + h * 3600_000).toISOString()

export const MOCK_CYCLES: CycleInfo[] = [
  {
    id: 'cetus',
    name: 'Cetus',
    state: 'night',
    timeLeft: '12m',
    expiry: inHours(0.2),
  },
  {
    id: 'vallis',
    name: 'Orb Vallis',
    state: 'cold',
    timeLeft: '8m',
    expiry: inHours(0.15),
  },
  {
    id: 'cambion',
    name: 'Cambion Drift',
    state: 'vome',
    timeLeft: '22m',
    expiry: inHours(0.35),
  },
]

export const MOCK_FISSURES: FissureInfo[] = [
  {
    id: 'f1',
    node: 'Ariel (Uranus)',
    missionType: 'Survival',
    enemy: 'Grineer',
    tier: 'Lith',
    eta: '45m',
    expiry: inHours(0.75),
    isHard: false,
  },
  {
    id: 'f2',
    node: 'Io (Jupiter)',
    missionType: 'Defense',
    enemy: 'Corpus',
    tier: 'Neo',
    eta: '1h',
    expiry: inHours(1),
    isHard: true,
  },
]

export const MOCK_BARO: BaroInfo = {
  active: true,
  location: 'Larunda Relay (Mercury)',
  arrival: inHours(-12),
  departure: inHours(36),
  eta: '1d 12h',
  inventory: [
    { uniqueName: '/Lotus/StoreItems/A', item: 'Primed Continuity', ducats: 350, credits: 100000 },
    { uniqueName: '/Lotus/StoreItems/B', item: 'Prisma Skana', ducats: 475, credits: 175000 },
  ],
}

export const MOCK_NIGHTWAVE: NightwaveInfo = {
  active: true,
  season: 17,
  tag: 'Nightwave Intermission · S17',
  expiry: inHours(72),
  phase: 0,
  challenges: [
    {
      id: 'daily-1',
      title: 'Sword Dance',
      description: 'Kill 150 Enemies with a Melee Weapon',
      reputation: 1000,
      isDaily: true,
      isElite: false,
      expiry: inHours(18),
    },
    {
      id: 'weekly-1',
      title: 'Eximus Eliminator',
      description: 'Kill 30 Eximus',
      reputation: 4500,
      isDaily: false,
      isElite: false,
      expiry: inHours(48),
    },
  ],
}

export const MOCK_ARBITRATION: ArbitrationInfo = {
  node: 'Tessera (Venus)',
  type: 'Defense',
  enemy: 'Corpus',
  expiry: inHours(1),
  eta: '1h',
}

/** Sample riven compare — used only in the Layout preview. */
export const MOCK_RIVEN_SCAN: RivenScanState = {
  active: true,
  scanning: false,
  scannedAt: new Date().toISOString(),
  trigger: 'manual',
  error: null,
  recommendation: 'take',
  current: {
    side: 'current',
    weapon: 'Lato',
    ocrText: '',
    score: 62,
    tier: 'B',
    stats: [
      {
        raw: '+Damage 168.2%',
        name: 'Damage',
        value: 168.2,
        unit: '%',
        negative: false,
        quality: 72,
        desirable: true,
      },
      {
        raw: '+Multishot 92.4%',
        name: 'Multishot',
        value: 92.4,
        unit: '%',
        negative: false,
        quality: 68,
        desirable: true,
      },
      {
        raw: '-Zoom 48.1%',
        name: 'Zoom',
        value: -48.1,
        unit: '%',
        negative: true,
        quality: 80,
        desirable: true,
      },
    ],
  },
  reroll: {
    side: 'reroll',
    weapon: 'Lato',
    ocrText: '',
    score: 84,
    tier: 'A',
    stats: [
      {
        raw: '+Critical Chance 187.6%',
        name: 'Critical Chance',
        value: 187.6,
        unit: '%',
        negative: false,
        quality: 88,
        desirable: true,
      },
      {
        raw: '+Critical Damage 142.3%',
        name: 'Critical Damage',
        value: 142.3,
        unit: '%',
        negative: false,
        quality: 86,
        desirable: true,
      },
      {
        raw: '+Multishot 110.8%',
        name: 'Multishot',
        value: 110.8,
        unit: '%',
        negative: false,
        quality: 82,
        desirable: true,
      },
      {
        raw: '-Reload Speed 36.2%',
        name: 'Reload Speed',
        value: -36.2,
        unit: '%',
        negative: true,
        quality: 55,
        desirable: false,
      },
    ],
  },
}

/** Sample fissure reward pick — used only in the Layout preview. */
export const MOCK_RELIC_REWARDS: RewardEval[] = [
  {
    slot: 0,
    ocrText: 'Nikana Prime Blade',
    name: 'Nikana Prime Blade',
    uniqueName: null,
    setName: 'Nikana Prime',
    partName: 'Blade',
    owned: 0,
    needed: true,
    setOwnedParts: 1,
    setTotalParts: 3,
    setParts: [],
    matchScore: 1,
    ducats: 65,
    platinum: 42,
    volume: 18,
    bestPick: true,
  },
  {
    slot: 1,
    ocrText: 'Forma Blueprint',
    name: 'Forma Blueprint',
    uniqueName: null,
    setName: null,
    partName: null,
    owned: 12,
    needed: false,
    setOwnedParts: 0,
    setTotalParts: 0,
    setParts: [],
    matchScore: 1,
    ducats: null,
    platinum: null,
    volume: null,
    bestPick: false,
  },
  {
    slot: 2,
    ocrText: 'Carrier Prime Systems',
    name: 'Carrier Prime Systems',
    uniqueName: null,
    setName: 'Carrier Prime',
    partName: 'Systems',
    owned: 2,
    needed: false,
    setOwnedParts: 3,
    setTotalParts: 3,
    setParts: [],
    matchScore: 1,
    ducats: 45,
    platinum: 12,
    volume: 40,
    bestPick: false,
  },
  {
    slot: 3,
    ocrText: 'Axi S8 Relic',
    name: 'Axi S8 Relic',
    uniqueName: null,
    setName: null,
    partName: null,
    owned: 4,
    needed: false,
    setOwnedParts: 0,
    setTotalParts: 0,
    setParts: [],
    matchScore: 0.8,
    ducats: null,
    platinum: null,
    volume: null,
    bestPick: false,
  },
]

export function buildPreviewWorldstate(live: WorldstateSnapshot): WorldstateSnapshot {
  return {
    fetchedAt: live.fetchedAt || new Date().toISOString(),
    error: live.error ?? null,
    stale: live.stale ?? false,
    cycles: live.cycles.length ? live.cycles : MOCK_CYCLES,
    fissures: live.fissures.length ? live.fissures : MOCK_FISSURES,
    baro: live.baro ?? MOCK_BARO,
    nightwave: live.nightwave ?? MOCK_NIGHTWAVE,
    arbitration: live.arbitration ?? MOCK_ARBITRATION,
    invasions: live.invasions?.length ? live.invasions : [],
    archonHunt: live.archonHunt,
    deepArchimedea: live.deepArchimedea,
  }
}
